server: 
  port: 8004

spring:
  elasticsearch:
    rest:
      uris: http://${ELASTICSEARCH_SERVER:127.0.0.1}:9200
  data:
    elasticsearch:
      cluster-nodes: ${ELASTICSEARCH_SERVER:127.0.0.1}:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true