server: 
  port: 8003

zookeeper:
  host: ${ZOOKEEPER_SERVER:localhost}:2181

kafka:
  bootstrap-servers: ${KAFKA_SERVER:localhost}:9092
  group: camelgroup
  topic:
    json:
      director: directortopic